### ISSUE TITLE
Allow to change visibility

### ISSUE THREAD

**Issue by ponychicken** [stadtwerk/google_maps_colorizr#1]
Please add a visibility toggle:

```
 stylers: [
       { visibility: "off" }
 ]
```

Possible values are: "off", "simplified" and "on"

**Comment by MarcKoester** [comment]
Hab ich eingebaut.

## 

stadt.werk | konzeption.text.gestaltung GmbH

Blocksberg 13 | Hinterhaus
24103 Kiel

t: +49.431.5192721
f: +49.431.5192724
m: info@stadtwerk.org
w: stadtwerk.org

"...wussten Sie schon, dass stadt.werk kein Energieversorger,
aber ein kreatives Energiezentrum ist?"

Geschäftsführung:
Stefan Conrad
Matthias Kran
Dr. Rolf Schwerdfeger

Handelsregister: HRB 11509
Registergericht: Kiel
Steuernummer: 1929210751

Am 18.08.2011 11:28, schrieb DieBuche:

> Please add a visibility toggle:
>      stylers: [
>            { visibility: "off" }
>      ]
> Possible values are: "off", "simplified" and "on"

**Comment by ponychicken** [comment]
Ein bisschen spät: Danke!
