### ISSUE TITLE
output color not matching hexadecimal value

### ISSUE THREAD

**Issue by millermedeiros** [stadtwerk/google_maps_colorizr#2]
input:

``` js
feature: water
element: all
color: "#6EB34A"
```

output:

``` js
hue: "#6EB34A"
saturation: 13
lightness: -29
```

hex of water: `#76C74B`

the same output values was generating proper color a couple weeks ago. it seems that Google Maps updated the color scheme so values aren't matching hex.

**Comment by millermedeiros** [comment]
I managed to get close to the color I wanted by using these settings:

``` js
hue: "#6EB34A"
saturation: -6
lightness: -35
```

output hex : `#6DB348`

**Comment by MarcKoester** [comment]
Google has changed their color base values.
I have updated the values. Should now work properly again.

## 

stadt.werk | konzeption.text.gestaltung GmbH

Blocksberg 13 | Hinterhaus
24103 Kiel

t: +49.431.5192721
f: +49.431.5192724
m: info@stadtwerk.org
w: stadtwerk.org

"...wussten Sie schon, dass stadt.werk kein Energieversorger,
aber ein kreatives Energiezentrum ist?"

Geschäftsführung:
Stefan Conrad
Matthias Kran
Dr. Rolf Schwerdfeger

Handelsregister: HRB 11509
Registergericht: Kiel
Steuernummer: 1929210751

Am 29.08.2011 20:28, schrieb millermedeiros:

> input:
> 
> ``` js
> feature: water
> element: all
> color: "#6EB34A"
> ```
> 
> output:
> 
> ``` js
> hue: "#6EB34A"
> saturation: 13
> lightness: -29
> ```
> 
> hex of water: `#76C74B`
> 
> the same output values was generating proper color a couple weeks ago. it seems that Google Maps updated the color scheme so values aren't matching hex.
